#!/sbin/busybox sh

# Reset LED bar
busybox echo '0' > /sys/class/leds/so34-led0/brightness
busybox echo '0' > /sys/class/leds/so34-led1/brightness
busybox echo '0' > /sys/class/leds/so34-led2/brightness

# In animaton
for i in $(seq 0 255)
do
    busybox echo $i > /sys/class/leds/so34-led0/brightness
    busybox echo $i > /sys/class/leds/so34-led1/brightness
    busybox echo $i > /sys/class/leds/so34-led2/brightness
done 

# Trigger vibration
busybox echo '50' > /sys/class/timed_output/vibrator/enable

# Out animaton
for i in $(seq 0 255)
do
    j=$((255 - $i))
    
    busybox echo $j > /sys/class/leds/so34-led0/brightness
    busybox echo $j > /sys/class/leds/so34-led1/brightness
    busybox echo $j > /sys/class/leds/so34-led2/brightnessss
done
